apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventprocessor
  namespace: {{ .Values.NAMESPACE }}
spec:
  selector:
    matchLabels:
      app: keygenerator
      component: eventprocessor
  template:
    metadata:
      labels:
        app: keygenerator
        component: eventprocessor
        aadpodidbinding: {{ .Values.MSI_SELECTOR  }} 
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000  
        supplementalGroups: [2000]
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: eventprocessor
        image: {{ print .Values.ACR_NAME "/keygenerator/eventprocessor:" .Values.COMMIT_VERSION }}
        imagePullPolicy: Always
        env:
        - name: EVENTHUB_CONNECTION__credential
          value: managedidentity
        - name: AzureFunctionsJobHost__functions__0
          value: CommandProcessing
        envFrom:
        - configMapRef:
            name: keygeneratorconfig
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.5"
            memory: 128Mi