ACR_NAME: ""
NAMESPACE: "default"
MSI_CLIENTID: ""
MSI_SELECTOR : ""
COMMIT_VERSION: "1.2"
EH_CONNECTION_STRING: "(EH Namespace name).servicebus.windows.net"
WEBJOB_STORAGE_ACCOUNT_NAME: "(Storage Name)"